name: TestingPlugin
version: '1.0-SNAPSHOT'
main: me.lavabucketman.testingplugin.TestingPlugin
api-version: 1.16
authors: [ LavaBucketMan ]
description: This is only for my testing plugin
website: https://github.com/62jdj
commands:
  god:
    description: Become invincible
    usage: /<command>
  feed:
    description: Feed yourself to the max hunger level
    usage: /<command>
